export default {
  projects: [
    {
      project: 'nabiboyd.com',
      website: 'https://nabiboyd.com/',
      tag: 'nabiboyd',
      type: 'website',
      year:  "2019",
      info: 'Website for Los Angeles based architecture and design studio nabiboyd. Interface as identity and identity as interface, the user is guided through the website by means of a navigation generated by the previous stacked moniker logo.',
      materials: 'Figma, VUE.JS, netlify',
      output: 'Website, identity, interface',
      images: [
        "/images/projects/nabiboyd/001.jpg",
        "/images/projects/nabiboyd/002.jpg",
        "/images/projects/nabiboyd/003.jpg",
      ]
    },
    {
      project: "Art Exchange",
      website: 'https://www.sharedstudios.com/herat',
      tag: 'art-exchange',
      type: 'identity',
      year:  "2019",
      info: 'Identity and graphics for Art Exchange, the third and final exhibition part of One Hundred for One Hundred, a collaborative curatorial project conceived to help commemorate the 100th anniversary of the Temescal Branch Library in Oakland, CA. Art Exchange consisted of exchanges between artists in Oakland, CA and Herat, Afghanistan through the Shared Studios shipping container platform.',
      materials: 'Figma, Illustrator',
      output: 'Identity, Graphics',
      images: [
        "/images/projects/artexchange/001.jpg",
        "/images/projects/artexchange/002.jpg",
        "/images/projects/artexchange/005.jpg",
        "/images/projects/artexchange/004.jpg",
        "/images/projects/artexchange/003.jpg",
      ]
    },
    {
      project: "omar's books",
      website: 'https://omarmhmmd.com/omarsbooks',
      tag: 'omars-books',
      type: 'website',
      year:  "2019",
      info: 'Omar’s Books is an Internet based simulacrum of the physical bookshelf acting at once as an archive to the books I’ve read since the end of 2017 and as a personal tool that allows me to view past reads when I’m not at my bookshelf in times of need. This allows for total recall when I can’t remember certain information or when I just want to visit what I’ve read visually in a holistic manner.',
      materials: 'Figma, HTML/CSS/JAVASCRIPT',
      output: 'Website, interface, archive',
      images: [
        "/images/projects/omarsbooks/001.jpg",
        "/images/projects/omarsbooks/002.jpg",
        "/images/projects/omarsbooks/003.jpg",
      ]
    },
    {
      project: "FWD:",
      tag: 'fwd',
      type: 'identity',
      year:  "2019",
      info: 'Identity, graphics, and signage for FWD:, the second exhibition part of One Hundred for One Hundred, a collaborative curatorial project conceived to help commemorate the 100th anniversary of the Temescal Branch Library in Oakland, CA.',
      materials: 'Figma, Illustrator, Newsprint, Paint',
      output: 'Identity, Graphics, Signage',
      images: [
        "/images/projects/fwd/001.jpg",
        "/images/projects/fwd/002.gif",
        "/images/projects/fwd/004.jpg",
        "/images/projects/fwd/005.jpg",
      ]
    },
    {
      project: 'elemental calder',
      tag: 'elemental-calder',
      type: 'exhibition',
      year: "2019",
      info: 'Exhibition graphics and identity for SFMOMA show "Elemental Calder". The works in this exhibition manifest the ways the elements—including the movement of the sea and the blowing of the wind—provided both subject matter and inspiration for many of Calder’s mobiles.',
      materials: 'Vinyl, Paint, 3D Letters',
      output: 'Identity, Graphics',
      images: [
        "/images/projects/elementalcalder/005.jpg",
        "/images/projects/elementalcalder/006.jpg",
        "/images/projects/elementalcalder/001.jpg",
        "/images/projects/elementalcalder/002.jpg",
        "/images/projects/elementalcalder/004.jpg",
      ]
    },
    {
      project: "Time capsule of tomorrows",
      tag: 'time-capsule-of-tomorrows',
      type: 'identity',
      year:  "2019",
      info: 'Identity and graphics for TCOT, the first exhibition part of One Hundred for One Hundred, a collaborative curatorial project conceived to help commemorate the 100th anniversary of the Temescal Branch Library in Oakland, CA.',
      materials: 'Figma, Illustrator',
      output: 'Identity, Graphics',
      images: [
        "/images/projects/tcot/001.jpg",
        "/images/projects/tcot/003.jpg",
        "/images/projects/tcot/002.jpg",
        "/images/projects/tcot/004.jpg",
        "/images/projects/tcot/005.jpg",
      ]
    },
    {
      project: 'SFMOMA TRASH/RECYCLING/COMPOST',
      tag: 'sfmoma-trash-recycling-compost',
      type: 'signage',
      year: "2019",
      info: 'Trash, recycling, and compost signage for bins located throughout SFMOMA that reflect brand and identity, while utilizing multiple languages as an accessibility feature.',
      materials: 'high-grade vinyl',
      output: '17" Vinyl prints',
      images: [
        "/images/projects/trashrecyclingcompost/010.jpg",
        "/images/projects/trashrecyclingcompost/007.jpg",
        "/images/projects/trashrecyclingcompost/011.jpg",
        "/images/projects/trashrecyclingcompost/004.jpg"
      ]
    },
    {
      project: 'suntar',
      website: 'https://omarmhmmd.suntar',
      tag: 'suntar',
      type: 'typeface',
      year:  "2018",
      info: 'SUNTAR 909 is a typeface inspired by found material discovered at an estate sale in El Cerrito, CA on September 23, 2018. A line of Super 8mm film viewers and editors, Suntar products were made in Japan by Sansei Koki circa 1970.',
      materials: 'Figma, VUE.JS, Robofont',
      output: 'Website, typeface, interface',
      images: [
        "/images/projects/suntar/001.jpg",
        "/images/projects/suntar/002.jpg",
        "/images/projects/suntar/003.jpg",
      ]
    },
    {
      project: '100sketches100buildings',
      website: 'http://100sketches100buildings.com/',
      tag: '100sketches-100buildings',
      type: 'website',
      year:  "2018",
      info: '100 Sketches by Omar Mohammad of 100 Buildings by Thom Mayne is an architectural drawing project that was created in response to the book 100 Buildings. These 100 sketches culminated in a website and an exhibition in a laundry room in Utah.',
      materials: 'Moleskine, Figma, VUE.JS',
      output: 'Website, exhibition, 100 sketches (5.5" x 8.5")',
      images: [
        "/images/projects/100sketches100buildings/001.jpg",
        "/images/projects/100sketches100buildings/002.jpg",
        "/images/projects/100sketches100buildings/003.jpg",
        "/images/projects/100sketches100buildings/004.jpg",
        "/images/projects/100sketches100buildings/005.jpg",
      ]
    },
    {
      project: 'Letterform archive',
      tag: 'letterform-online-archive',
      website: 'https://letterformarchive.org/news/announcing-the-online-archive',
      type: 'website',
      year: "2018",
      info: 'Online digital archive designed and programmed with Jon Sueda and Chris Hamamoto for San Francisco based graphic design archive and collection.',
      materials: 'figma, html/css/javascript',
      output: 'website, interface',
      images: [
        "/images/projects/letterformarchive/001.jpg",
        "/images/projects/letterformarchive/002.jpg",
        "/images/projects/letterformarchive/003.jpg"
      ]
    },
    {
      project: 'Rethink: Web',
      tag: 'rethink-web',
      website: 'http://oldlab.sfmoma.org/rethink-web-graphics/',
      type: 'identity',
      year: "2018",
      info: 'The Rethink: Web logo is designed as a symbol regarding the speculative future of the relationship between the web and the grid. Through this web based application, designers of the Rethink: Web workshops were encouraged to create a new "logo" for each project created during the workshop, allowing for the design system of Rethink: Web to be a continuous and ever-changing system, just like the web.',
      materials: 'figma, html/css/javascript',
      output: 'identity, graphic tool, website',
      images: [
        "/images/projects/rethinkweb/005.gif",
        // "/images/projects/rethinkweb/002.jpg",
        "/images/projects/rethinkweb/003.jpg"
      ]
    },
    {
      project: 'josefAlbersBot',
      tag: 'josef-albers-bot',
      website: 'https://twitter.com/josefAlbersBot',
      type: 'bot',
      year: "2017",
      info: 'JOSEFALBERSBOT is a twitter bot that takes on the spirit of Bauhaus artist Josef Albers. With this twitter bot, questions about Alber’s existence in the 21st century are explored: with the ease of illustration and automation how would Albers go about creating his revolutionary pieces? Have his pieces ever held figurative meanings within their abstractions?',
      materials: 'Raspberry Pi, Javascript',
      output: 'twitter bot',
      images: [
        "/images/projects/josefalbersbot/001.jpg",
        "/images/projects/josefalbersbot/002.jpg",
        "/images/projects/josefalbersbot/003.jpg"
      ]
    },
    {
      project: 'omarmhmmd.com (v1)',
      tag: 'omarmhmmd-v1',
      website: 'https://omarmhmmd.com/omarmhmmd-v1',
      type: 'website',
      year: "2017",
      info: 'The first portfolio website I built for myself (you are currently on the second). Using no framework, maintenance and updating became quite difficult so I had to move on. When loaded projects are animated through a gradient of a single color which is randomly generated each time.',
      materials: 'figma, html/css/javascript',
      output: 'website, interface',
      images: [
        "/images/projects/omarmhmmd/001.jpg",
        "/images/projects/omarmhmmd/002.jpg",
        "/images/projects/omarmhmmd/003.jpg"
      ]
    },
    {
      project: 'qiblah',
      tag: 'qiblah',
      website: 'https://vimeo.com/246914053',
      type: 'object',
      year: "2017",
      info: ' Qiblah is a speculative prototype design that explores anti-interface technology. The qiblah is the direction towards the Ka\'aba which Muslims face towards while praying. Today many smart phone apps are responsible for guiding Muslims towards the correct qiblah. Qiblah was designed as an analog alternative, enabling holy spaces to be untouched by the distractions of higher technology.',
      materials: 'Raspberry Pi, Node.js, LED, Wood, Acrylic',
      output: 'object, interface',
      images: [
        "/images/projects/qiblah/006.jpg",
        "/images/projects/qiblah/003.jpg",
        "/images/projects/qiblah/004.jpg",
        "/images/projects/qiblah/005.gif",
        "/images/projects/qiblah/001.jpg",
      ]
    },
    {
      project: 'sfmomabathrooms',
      tag: 'sfmomabathrooms',
      website: 'http://sfmomabathrooms.com/',
      type: 'website',
      year: "2017",
      info: 'Sfmomabathrooms is an interactive and print experience presenting the bathrooms located at the San Francisco Museum of Modern Art. These bathrooms extend the experience of the museum into liminal spaces that usually take no part in an experience of art.',
      materials: 'Figma, HTML/CSS/JAVASCRIPT, Contax t2',
      output: 'Website, 5.5" x 8.5" Book (32pg)',
      images: [
        "/images/projects/sfmomabathrooms/001.png",
        "/images/projects/sfmomabathrooms/002.png",
        "/images/projects/sfmomabathrooms/003.png",
        "/images/projects/sfmomabathrooms/004.gif"
      ]
    },
    {
      project: 'pilgrim',
      tag: 'pilgrim',
      website: 'https://omarmhmmd.itch.io/pilgrim',
      type: 'video game',
      year: "2017",
      info: 'Pilgrim is a video game that abstracts the process that is Hajj, the Islamic pilgrimage to Mecca. Through 2D references to certain steps and events that make up Hajj, the procedural rhetoric of one of the 5 pillars of Islam is conveyed through digital and visual means.',
      materials: 'Unity, C#',
      output: 'Video game, code',
      images: [
        "/images/projects/pilgrim/002.jpg",
        "/images/projects/pilgrim/003.jpg",
        "/images/projects/pilgrim/004.jpg",
        "/images/projects/pilgrim/005.jpg"
      ]
    },
  ]
}
