export default {
  projects: [
    {
      project: 'elemental calder',
      tag: 'elemental-calder',
      type: 'exhibition',
      year: "2019",
      info: 'Exhibition graphics and identity for SFMOMA show "Elemental Calder". The works in this exhibition manifest the ways the elements—including the movement of the sea and the blowing of the wind—provided both subject matter and inspiration for many of Calder’s mobiles.',
      materials: 'Vinyl, Paint, 3D Letters',
      output: 'Identity, Graphics',
      images: [
        "/images/projects/elementalcalder/005.jpg",
        "/images/projects/elementalcalder/006.jpg",
        "/images/projects/elementalcalder/001.jpg",
        "/images/projects/elementalcalder/002.jpg",
        "/images/projects/elementalcalder/004.jpg",
      ]
    },
    {
      project: 'nabiboyd.com',
      website: 'https://nabiboyd.com/',
      tag: 'nabiboyd',
      type: 'website',
      year:  "2019",
      info: 'Website for Los Angeles based architecture and design studio nabiboyd. Interface as identity and identity as interface, the user is guided through the website by means of a navigation generated by the previous studio logo.',
      materials: 'Figma, VUE.JS, netlify',
      output: 'Website, identity, interface',
      images: [
        "/images/projects/nabiboyd/001.png",
        "/images/projects/nabiboyd/002.png",
        "/images/projects/nabiboyd/003.png",
      ]
    },
    {
      project: 'SFMOMA TRASH/RECYCLING/COMPOST',
      tag: 'sfmoma-trash-recycling-compost',
      type: 'signage',
      year: "2019",
      info: 'Trash, recycling, and compost signage for bins located throughout SFMOMA that reflect brand and identity, while utilizing multiple languages as an accessibility feature.',
      materials: 'high-grade vinyl',
      output: '17" Vinyl prints',
      images: [
        "/images/projects/trashrecyclingcompost/010.png",
        "/images/projects/trashrecyclingcompost/007.png",
        "/images/projects/trashrecyclingcompost/011.png",
        "/images/projects/trashrecyclingcompost/004.png"
      ]
    },
    {
      project: 'suntar',
      website: 'http://omarmhmmd.com/suntar/',
      tag: 'suntar',
      type: 'typeface',
      year:  "2019",
      info: 'SUNTAR 909 is a typeface inspired by found material discovered at an estate sale in El Cerrito, CA on September 23, 2018. A line of Super 8mm film viewers and editors, Suntar products were made in Japan by Sansei Koki circa 1970.',
      materials: 'Figma, VUE.JS, Robofont',
      output: 'Website, typeface, interface',
      images: [
        "/images/projects/suntar/001.png",
        "/images/projects/suntar/002.png",
        "/images/projects/suntar/003.png",
      ]
    },
    {
      project: 'Letterform archive',
      tag: 'letterform-online-archive',
      website: 'https://letterformarchive.org/news/announcing-the-online-archive',
      type: 'website',
      year: "2018",
      info: 'Online digital archive designed and programmed with Jon Sueda and Chris Hamamoto for San Francisco based graphic design archive and collection.',
      materials: 'figma, html/css/javascript',
      output: 'website, interface',
      images: [
        "/images/projects/letterformarchive/001.png",
        "/images/projects/letterformarchive/002.png",
        "/images/projects/letterformarchive/003.png"
      ]
    },
    {
      project: 'Rethink: Web',
      tag: 'rething-web',
      website: 'http://oldlab.sfmoma.org/rethink-web-graphics/',
      type: 'identity',
      year: "2018",
      info: 'The Rethink: Web logo was designed as a symbol regarding the speculative future of the relationship between the web and the grid. Through this web based application, designers of the Rethink: Web workshops were encouraged to create a new "logo" for each project created during the workshop, allowing for the design system of Rethink: Web to be a continuous and ever-changing system, just like the web.',
      materials: 'figma, html/css/javascript',
      output: 'identity, graphic tool, website',
      images: [
        "/images/projects/rethinkweb/005.gif",
        "/images/projects/rethinkweb/002.png",
        "/images/projects/rethinkweb/003.png"
      ]
    },
    // {
    //   project: 'shadezine.com',
    //   tag: 'shade-zine',
    //   website: 'https://omarmhmmd.github.io/shadezine.com/',
    //   type: 'website',
    //   year: "2018",
    //   info: 'Website for Oakland based creative duo SHADEZINE aka Azha Luckman & Apryl Fuentes. After a shift in creative vision, shadezine decided to shut down this website shortly after it was created.',
    //   materials: 'figma, html/css/javascript',
    //   output: 'website, interface',
    //   images: [
    //     "/images/projects/shadezine/001.gif",
    //     "/images/projects/shadezine/002.gif",
    //     // "/images/projects/shadezine/003.mp4"
    //   ]
    // },
    {
      project: 'josefAlbersBot',
      tag: 'josef-albers-bot',
      website: 'https://twitter.com/josefAlbersBot',
      type: 'bot',
      year: "2017",
      info: 'JOSEFALBERSBOT is a twitter bot that takes on the spirit of Bauhaus artist Josef Albers. With this twitter bot, questions about Alber’s existence in the 21st century are explored: with the ease of illustration and automation how would Albers go about creating his revolutionary pieces? Have his pieces ever held figurative meanings within their abstractions?',
      materials: 'Raspberry Pi, Javascript',
      output: 'twitter bot',
      images: [
        "/images/projects/josefalbersbot/001.png",
        "/images/projects/josefalbersbot/002.png",
        "/images/projects/josefalbersbot/003.png"
      ]
    },
    {
      project: 'omarmhmmd.com (v1)',
      tag: 'omarmhmmd-v1',
      website: 'https://omarmhmmd.github.io/omarmhmmd/',
      type: 'website',
      year: "2017",
      info: 'The first portfolio website I built for myself (you are currently on the second). Using no framework, maintenance and updating became quite difficult so I had to move forward. When loaded projects are animated through a gradient of a single color which is randomly generated each time.',
      materials: 'figma, html/css/javascript',
      output: 'website, interface',
      images: [
        "/images/projects/omarmhmmd/001.png",
        "/images/projects/omarmhmmd/002.png",
        "/images/projects/omarmhmmd/003.png"
      ]
    },
    {
      project: 'qiblah',
      tag: 'qiblah',
      website: 'https://vimeo.com/246914053',
      type: 'object',
      year: "2017",
      info: ' Qiblah is a speculative prototype design that explores anti-interface technology. The qiblah is the direction towards the Ka\'aba which Muslims face towards while praying. Today many smart phone apps are responsible for guiding Muslims towards the correct qiblah. Qiblah was designed as an analog alternative, enabling holy spaces to be untouched by the distractions of higher technology.',
      materials: 'Raspberry Pi, Node.js, LED, Wood, Acrylic',
      output: 'object, interface',
      images: [
        "/images/projects/qiblah/006.png",
        "/images/projects/qiblah/003.png",
        "/images/projects/qiblah/004.png",
        "/images/projects/qiblah/005.gif",
        "/images/projects/qiblah/001.png",
      ]
    },
    {
      project: 'sfmomabathrooms',
      tag: 'sfmomabathrooms',
      website: 'http://sfmomabathrooms.com/',
      type: 'website',
      year: "2017",
      info: 'Sfmomabathrooms is an interactive and print experience presenting the bathrooms located at the San Francisco Museum of Modern Art. These bathrooms extend the experience of the museum into liminal spaces that usually take no part in an experience of art.',
      materials: 'Figma, HTML/CSS/JAVASCRIPT, Contax t2',
      output: 'Website, 5.5" x 8.5" Book (32pg)',
      images: [
        "/images/projects/sfmomabathrooms/001.png",
        "/images/projects/sfmomabathrooms/002.png",
        "/images/projects/sfmomabathrooms/003.png",
        "/images/projects/sfmomabathrooms/004.gif"
      ]
    },
    {
      project: 'pilgrim',
      tag: 'pilgrim',
      website: 'https://omarmhmmd.itch.io/pilgrim',
      type: 'video game',
      year: "2016",
      info: 'Pilgrim is a video game that abstracts the process that is Hajj, the Islamic pilgrimage to Mecca. Through 2D references to certain steps and events that make up Hajj, the procedural rhetoric of one of the 5 pillars of Islam is conveyed through digital and visual means.',
      materials: 'Unity, C#',
      output: 'Video game, code',
      images: [
        "/images/projects/pilgrim/002.png",
        "/images/projects/pilgrim/003.png",
        "/images/projects/pilgrim/004.png",
        "/images/projects/pilgrim/005.png"
      ]
    },
  ]
}
